/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PartnershipRouteImport } from './routes/partnership'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as SecretariatRouteImport } from './routes/secretariat'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityImpactRouteImport } from './routes/community-impact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretariatRoute = SecretariatRouteImport.update({
  id: '/secretariat',
  path: '/secretariat',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipRoute = PartnershipRouteImport.update({
  id: '/partnership',
  path: '/partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityImpactRoute = CommunityImpactRouteImport.update({
  id: '/community-impact',
  path: '/community-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community-impact': typeof CommunityImpactRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/leadership': typeof LeadershipRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRouteWithChildren
  '/partnership': typeof PartnershipRoute
  '/secretariat': typeof SecretariatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community-impact': typeof CommunityImpactRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/leadership': typeof LeadershipRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRouteWithChildren
  '/partnership': typeof PartnershipRoute
  '/secretariat': typeof SecretariatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community-impact': typeof CommunityImpactRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/leadership': typeof LeadershipRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRouteWithChildren
  '/partnership': typeof PartnershipRoute
  '/secretariat': typeof SecretariatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community-impact'
    | '/contact'
    | '/events'
    | '/leadership'
    | '/membership'
    | '/news'
    | '/partnership'
    | '/secretariat'
    | '/sitemap.xml'
    | '/news/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community-impact'
    | '/contact'
    | '/events'
    | '/leadership'
    | '/membership'
    | '/news'
    | '/partnership'
    | '/secretariat'
    | '/sitemap.xml'
    | '/news/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community-impact'
    | '/contact'
    | '/events'
    | '/leadership'
    | '/membership'
    | '/news'
    | '/partnership'
    | '/secretariat'
    | '/sitemap.xml'
    | '/news/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityImpactRoute: typeof CommunityImpactRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  LeadershipRoute: typeof LeadershipRoute
  MembershipRoute: typeof MembershipRoute
  NewsRoute: typeof NewsRouteWithChildren
  PartnershipRoute: typeof PartnershipRoute
  SecretariatRoute: typeof SecretariatRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretariat': {
      id: '/secretariat'
      path: '/secretariat'
      fullPath: '/secretariat'
      preLoaderRoute: typeof SecretariatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnership': {
      id: '/partnership'
      path: '/partnership'
      fullPath: '/partnership'
      preLoaderRoute: typeof PartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretariat': {
      id: '/secretariat'
      path: '/secretariat'
      fullPath: '/secretariat'
      preLoaderRoute: typeof SecretariatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-impact': {
      id: '/community-impact'
      path: '/community-impact'
      fullPath: '/community-impact'
      preLoaderRoute: typeof CommunityImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
  }
}

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityImpactRoute: CommunityImpactRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  LeadershipRoute: LeadershipRoute,
  MembershipRoute: MembershipRoute,
  NewsRoute: NewsRouteWithChildren,
  PartnershipRoute: PartnershipRoute,
  SecretariatRoute: SecretariatRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
